# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
    - task: build

  build:
    cmds:
    - go build -o ./.bin/todo ./cmd/todo/main.go

  run:
    cmds:
    - go run ./cmd/todo/main.go
